name: build susfs_userspace

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: source-code

      - name: grab ndk
        run: |
          curl -L https://dl.google.com/android/repository/android-ndk-r23b-linux.zip -o ndk-linux.zip
          unzip ndk-linux.zip

      - name: grab zig
        run: |
          curl -L https://ziglang.org/download/0.14.1/zig-x86_64-linux-0.14.1.tar.xz -o zig.tar.xz
          tar -xf zig.tar.xz
          mv zig-* zig

      - name: grab sstrip from ELFkickers
        run: |
          curl -L https://www.muppetlabs.com/~breadbox/pub/software/ELFkickers-3.2.tar.gz -o sstrip.tar.gz
          tar xf sstrip.tar.gz
          make -C ELFkickers-3.2 sstrip
          cp ELFkickers-3.2/sstrip/sstrip .

      - name: compile via zigcc
        run: |
          ls -la ; pwd
          echo "for now only aarch64 is built"
          chmod +x sstrip

          for i in {152..159}; do
            mkdir -p binaries/$i/gki/
            mkdir -p binaries/$i/non-gki/
          done
          
          for i in {152..159}; do
            # Compile GKI version
            ./zig/zig cc -target aarch64-linux -s -Oz $i/gki/main.c -static -s -Wl,--gc-sections -o binaries/$i/gki/ksu_susfs_arm64 -I ./android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
            
            # Compile non-GKI version
            ./zig/zig cc -target aarch64-linux -s -Oz $i/ngki/main.c -static -s -Wl,--gc-sections -o binaries/$i/non-gki/ksu_susfs_arm64 -I ./android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
          done

          upx --ultra-brute binaries/*/*/ksu_susfs_arm64
          for i in binaries/*/*/ksu_susfs_arm64; do ./sstrip $i ; done;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: susfs_binaries
          path: binaries/

